[ 2025-01-17 21:38:26,801 ] 28 root - INFO - Entered the data ingestion method.
[ 2025-01-17 21:38:26,807 ] 33 root - INFO - Dataset loaded successfully as a DataFrame.
[ 2025-01-17 21:38:26,812 ] 40 root - INFO - Raw data saved successfully.
[ 2025-01-17 21:38:26,819 ] 47 root - INFO - Train and test datasets created and saved successfully.
[ 2025-01-17 21:38:26,819 ] 63 root - INFO - Data ingestion completed. Train data: artifacts\train.csv, Test data: artifacts\test.csv
[ 2025-01-17 21:38:26,847 ] 74 root - INFO - Train and test datasets loaded successfully.
[ 2025-01-17 21:38:26,847 ] 51 root - INFO - Numerical columns preprocessing pipeline created.
[ 2025-01-17 21:38:26,851 ] 89 root - INFO - Preprocessing object applied to training and testing datasets.
[ 2025-01-17 21:38:26,863 ] 98 root - INFO - Saving preprocessing object.
[ 2025-01-17 21:38:26,865 ] 37 root - INFO - split train and test input data
[ 2025-01-17 21:38:26,865 ] 74 root - ERROR - CustomException occurred: Error occurred in Python script name [C:\Users\KRINSI\OneDrive\Desktop\MLproject\src\components\model_trainer.py] line number [48] error message [name 'RandomForestRegressor' is not defined]
